const students = [
  {
    firstName: "Amy",
    lastName: "Johnson",
    email: "amy.johnson@example.com",
    graduationYear: 2026,
    gpa: 3.9,
  },
  {
    firstName: "Brian",
    lastName: "Lee",
    email: "brian.lee@example.com",
    graduationYear: 2025,
    gpa: 3.7,
  },
  {
    firstName: "Sophia",
    lastName: "Martinez",
    email: "sophia.martinez@example.com",
    graduationYear: 2026,
    gpa: 4.0,
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    graduationYear: 2027,
    gpa: 3.5,
  },
  {
    firstName: "Emma",
    lastName: "Davis",
    email: "emma.davis@example.com",
    graduationYear: 2026,
    gpa: 3.8,
  },
  {
    firstName: "Daniel",
    lastName: "Wilson",
    email: "daniel.wilson@example.com",
    graduationYear: 2025,
    gpa: 3.6,
  },
  {
    firstName: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@example.com",
    graduationYear: 2027,
    gpa: 3.9,
  },
  {
    firstName: "James",
    lastName: "Anderson",
    email: "james.anderson@example.com",
    graduationYear: 2026,
    gpa: 3.4,
  },
  {
    firstName: "Charlotte",
    lastName: "Thomas",
    email: "charlotte.thomas@example.com",
    graduationYear: 2025,
    gpa: 3.8,
  },
  {
    firstName: "Benjamin",
    lastName: "Moore",
    email: "benjamin.moore@example.com",
    graduationYear: 2026,
    gpa: 3.7,
  },
  {
    firstName: "Mia",
    lastName: "Martin",
    email: "mia.martin@example.com",
    graduationYear: 2027,
    gpa: 4.0,
  },
  {
    firstName: "Lucas",
    lastName: "Jackson",
    email: "lucas.jackson@example.com",
    graduationYear: 2025,
    gpa: 3.5,
  },
  {
    firstName: "Harper",
    lastName: "White",
    email: "harper.white@example.com",
    graduationYear: 2026,
    gpa: 3.9,
  },
  {
    firstName: "Ethan",
    lastName: "Harris",
    email: "ethan.harris@example.com",
    graduationYear: 2027,
    gpa: 3.6,
  },
  {
    firstName: "Grace",
    lastName: "Clark",
    email: "grace.clark@example.com",
    graduationYear: 2026,
    gpa: 3.8,
  },
  {
    firstName: "Noah",
    lastName: "Lewis",
    email: "noah.lewis@example.com",
    graduationYear: 2025,
    gpa: 3.7,
  },
  {
    firstName: "Isabella",
    lastName: "Walker",
    email: "isabella.walker@example.com",
    graduationYear: 2026,
    gpa: 3.9,
  },
  {
    firstName: "Henry",
    lastName: "Hall",
    email: "henry.hall@example.com",
    graduationYear: 2027,
    gpa: 3.3,
  },
  {
    firstName: "Ava",
    lastName: "Allen",
    email: "ava.allen@example.com",
    graduationYear: 2025,
    gpa: 3.8,
  },
  {
    firstName: "William",
    lastName: "Young",
    email: "william.young@example.com",
    graduationYear: 2026,
    gpa: 3.6,
  },
];

const colleges = [
  {
    name: "Massachusetts Institute of Technology",
    city: "Cambridge",
    state: "MA",
    applicationDeadline: new Date("2026-01-01"),
    applicationFee: 75,
    acceptanceRate: 4.8,
    website: "https://web.mit.edu",
  },
  {
    name: "Stanford University",
    city: "Stanford",
    state: "CA",
    applicationDeadline: new Date("2026-01-05"),
    applicationFee: 90,
    acceptanceRate: 3.9,
    website: "https://www.stanford.edu",
  },
  {
    name: "University of Michigan",
    city: "Ann Arbor",
    state: "MI",
    applicationDeadline: new Date("2026-02-01"),
    applicationFee: 65,
    acceptanceRate: 18,
    website: "https://umich.edu",
  },
  {
    name: "University of California Berkeley",
    city: "Berkeley",
    state: "CA",
    applicationDeadline: new Date("2026-01-15"),
    applicationFee: 80,
    acceptanceRate: 14,
    website: "https://www.berkeley.edu",
  },
  {
    name: "Georgia Institute of Technology",
    city: "Atlanta",
    state: "GA",
    applicationDeadline: new Date("2026-01-10"),
    applicationFee: 75,
    acceptanceRate: 16,
    website: "https://www.gatech.edu",
  },
  {
    name: "Princeton University",
    city: "Princeton",
    state: "NJ",
    applicationDeadline: new Date("2026-01-01"),
    applicationFee: 80,
    acceptanceRate: 5.7,
    website: "https://www.princeton.edu",
  },
  {
    name: "Harvard University",
    city: "Cambridge",
    state: "MA",
    applicationDeadline: new Date("2026-01-01"),
    applicationFee: 85,
    acceptanceRate: 4,
    website: "https://www.harvard.edu",
  },
  {
    name: "Yale University",
    city: "New Haven",
    state: "CT",
    applicationDeadline: new Date("2026-01-02"),
    applicationFee: 80,
    acceptanceRate: 4.6,
    website: "https://www.yale.edu",
  },
  {
    name: "Columbia University",
    city: "New York",
    state: "NY",
    applicationDeadline: new Date("2026-01-04"),
    applicationFee: 85,
    acceptanceRate: 3.9,
    website: "https://www.columbia.edu",
  },
  {
    name: "New York University",
    city: "New York",
    state: "NY",
    applicationDeadline: new Date("2026-01-05"),
    applicationFee: 85,
    acceptanceRate: 12.5,
    website: "https://www.nyu.edu",
  },
  {
    name: "Boston University",
    city: "Boston",
    state: "MA",
    applicationDeadline: new Date("2026-01-06"),
    applicationFee: 80,
    acceptanceRate: 19,
    website: "https://www.bu.edu",
  },
  {
    name: "Northeastern University",
    city: "Boston",
    state: "MA",
    applicationDeadline: new Date("2026-01-10"),
    applicationFee: 75,
    acceptanceRate: 18,
    website: "https://www.northeastern.edu",
  },
  {
    name: "Rutgers University",
    city: "New Brunswick",
    state: "NJ",
    applicationDeadline: new Date("2026-01-15"),
    applicationFee: 70,
    acceptanceRate: 68,
    website: "https://www.rutgers.edu",
  },
  {
    name: "Penn State University",
    city: "University Park",
    state: "PA",
    applicationDeadline: new Date("2026-01-15"),
    applicationFee: 65,
    acceptanceRate: 55,
    website: "https://www.psu.edu",
  },
  {
    name: "Temple University",
    city: "Philadelphia",
    state: "PA",
    applicationDeadline: new Date("2026-02-01"),
    applicationFee: 55,
    acceptanceRate: 72,
    website: "https://www.temple.edu",
  },
  {
    name: "Drexel University",
    city: "Philadelphia",
    state: "PA",
    applicationDeadline: new Date("2026-01-15"),
    applicationFee: 65,
    acceptanceRate: 79,
    website: "https://www.drexel.edu",
  },
  {
    name: "University of Maryland",
    city: "College Park",
    state: "MD",
    applicationDeadline: new Date("2026-01-20"),
    applicationFee: 75,
    acceptanceRate: 44,
    website: "https://www.umd.edu",
  },
  {
    name: "Johns Hopkins University",
    city: "Baltimore",
    state: "MD",
    applicationDeadline: new Date("2026-01-03"),
    applicationFee: 75,
    acceptanceRate: 7,
    website: "https://www.jhu.edu",
  },
  {
    name: "Syracuse University",
    city: "Syracuse",
    state: "NY",
    applicationDeadline: new Date("2026-01-05"),
    applicationFee: 85,
    acceptanceRate: 59,
    website: "https://www.syracuse.edu",
  },
  {
    name: "Stevens Institute of Technology",
    city: "Hoboken",
    state: "NJ",
    applicationDeadline: new Date("2026-01-15"),
    applicationFee: 70,
    acceptanceRate: 46,
    website: "https://www.stevens.edu",
  },
];


export default {
  students,
  colleges,
};